version: "3.8"

services:
  database:
    image: mysql:8.0
    container_name: kiosk_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: osijek_kiosk
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  server:
    build: ./server
    container_name: kiosk_server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    environment:
      - DB_HOST=database
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      database:
        condition: service_healthy
    restart: always

  client:
    build: ./client
    container_name: kiosk_client
    ports:
      - "8081:8081"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    restart: always

volumes:
  mysql_data:
